name: Build and Publish

on:
  push:
    branches: [ master, anamnesis ]
    tags:
      - '*'
  pull_request:
    branches: [ master, anamnesis ]
  workflow_dispatch:

env: 
  SOLUTION_PATH: ./source/Reloaded.Hooks.sln
  NUPKG_GLOB: ./source/Reloaded.Hooks/bin/Release/*.nupkg
  IS_RELEASE: ${{ startsWith(github.ref, 'refs/tags/') }}

jobs:
  build:
    runs-on: windows-2022
    defaults:
      run:
        shell: pwsh

    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Get Dotnet Info
      run: dotnet --info

    - name: Build
      run: dotnet build -c Release "$env:SOLUTION_PATH"

    - name: Test
      run: |
           dotnet tool install --global altcover.global --version 8.2.833
           $ipmo = (AltCover ImportModule | Out-String)
           Invoke-Expression $ipmo
    
           dotnet test -f net6.0 .\source\Reloaded.Hooks.Tests.X86\Reloaded.Hooks.Tests.X86.csproj /p:AltCover=true /p:CopyLocalLockFileAssemblies="true" /p:AltCoverAttributeFilter="ExcludeFromCodeCoverageAttribute" /p:AltCoverAssemblyExcludeFilter="Reloaded.Hooks.Tests.X86|Reloaded.Hooks.Tests.X64|Reloaded.Hooks.Tests.Shared|xunit\.*" /p:AltCoverTypeFilter="xunit\.*|AltCover\.*|Reloaded\.Assembler.*" /p:AltCoverReport="../../coverage-86.xml"
           dotnet test -f net6.0 .\source\Reloaded.Hooks.Tests.X64\Reloaded.Hooks.Tests.X64.csproj /p:AltCover=true /p:CopyLocalLockFileAssemblies="true" /p:AltCoverAttributeFilter="ExcludeFromCodeCoverageAttribute" /p:AltCoverAssemblyExcludeFilter="Reloaded.Hooks.Tests.X86|Reloaded.Hooks.Tests.X64|Reloaded.Hooks.Tests.Shared|xunit\.*" /p:AltCoverTypeFilter="xunit\.*|AltCover\.*|Reloaded\.Assembler.*" /p:AltCoverReport="../../coverage-64.xml"

    - name: Upload NuGet Package Artifact
      uses: actions/upload-artifact@v4
      with:
        name: NuGet Packages
        path: ${{ env.NUPKG_GLOB }}

    - name: Upload to NuGet (on Tag)
      env: 
        NUGET_KEY: ${{ secrets.NUGET_KEY }}
      if: env.IS_RELEASE == 'true'
      run: |
        $items = Get-ChildItem -Path "$env:NUPKG_GLOB"
        Foreach ($item in $items)
        {
            Write-Host "Pushing $item"
            dotnet nuget push "$item" -k "$env:NUGET_KEY" -s "https://api.nuget.org/v3/index.json" --skip-duplicate
        }

    - name: Create Draft Release
      if: env.IS_RELEASE == 'true'
      uses: softprops/action-gh-release@v2
      with:
        draft: true
        files: ${{ env.NUPKG_GLOB }}
        generate_release_notes: true
